name: build
on:
  push:
    branches: [ master ]
    paths:
      - api/**
      - gameserver/**
      - shared/**
      - src/**
      - build.gradle
  pull_request:
    branches: [ master ]
    paths:
      - api/**
      - gameserver/**
      - shared/**
      - src/**
      - build.gradle
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: brainwine
        path: build/distributions/**
